name: MBTHLoginSecurity
version: 1.0.1
main: com.mbth.loginsecurity.MBTHLoginSecurity
api-version: 1.21
author: MBTH Development
description: Advanced login security system with session hijacking protection
website: https://mbth.dev
softdepend: [DiscordSRV]

commands:
  register:
    description: Register a new account
    usage: /register <password> <confirm-password>
    aliases: [reg]
  
  login:
    description: Login to your account
    usage: /login <password>
    aliases: [l]
  
  changepassword:
    description: Change your account password
    usage: /changepassword <old-password> <new-password> <confirm-new>
    aliases: [changepass, chpass]
  
  setuppin:
    description: Setup a PIN code for extra security
    usage: /setuppin <pin> <confirm-pin>
    aliases: [setpin, createpin]
  
  verifypin:
    description: Verify your PIN code
    usage: /verifypin <pin>
    aliases: [pin, enterpin]
  
  changepin:
    description: Change your PIN code
    usage: /changepin <old-pin> <new-pin> <confirm-new>
    aliases: [modifypin]
  
  resetpin:
    description: Admin command to reset a player's PIN
    usage: /resetpin <player>
    aliases: [pinreset]
    permission: mbth.admin
  
  resetpassword:
    description: Admin command to reset a player's password
    usage: /resetpassword <player> <new-password>
    aliases: [resetpass, passreset]
    permission: mbth.admin
  
  unregister:
    description: Admin command to unregister a player's account
    usage: /unregister <player>
    aliases: [unreg, deleteaccount]
    permission: mbth.admin
  
  freezeaccount:
    description: Freeze a player's account preventing login
    usage: /freezeaccount <player>
    aliases: [freeze, lockaccount]
    permission: mbth.admin
  
  unfreezeaccount:
    description: Unfreeze a player's account
    usage: /unfreezeaccount <player>
    aliases: [unfreeze, unlockaccount]
    permission: mbth.admin
  
  forcelogout:
    description: Force logout an authenticated player
    usage: /forcelogout <player>
    aliases: [forcelog, logout]
    permission: mbth.admin
  
  checkalt:
    description: Check for alt accounts of a player
    usage: /checkalt <player>
    aliases: [checkalts, alts]
    permission: mbth.admin
  
  mbthlsreload:
    description: Reload the plugin configuration
    usage: /mbthlsreload
    aliases: [mbthlsr, reloadmbthls]
    permission: mbth.admin

permissions:
  mbth.admin:
    description: Administrator permissions for password reset
    default: op