# MBTH Login Security Configuration

# Server/Network Name (Customizable branding)
server-name: "MBTH"

# Title Customization
titles:
  # Main title shown on join (supports color codes with &)
  main-title: "&6✦ &e&lMBTH Security &6✦"
  
  # Subtitle shown below main title
  subtitle: "&ePlease login to continue"
  
  # Scoreboard/Action bar title
  scoreboard-title: "&6&lMBTH LOGIN SECURITY"

# Maximum number of failed login attempts before kick
max-login-attempts: 3

# Time in seconds before player is kicked for not logging in
login-timeout-seconds: 60

# Session settings
session:
  # Enable session persistence (players stay logged in after rejoining)
  enabled: true
  
  # Session duration in minutes
  duration-minutes: 30

# Alt account detection
alt-detection:
  # Enable automatic alt account detection via IP tracking
  enabled: true
  
  # Notify admins when alt accounts are detected
  notify-admins: true

# Premium/Cracked Player Detection
premium-bypass:
  # Enable automatic bypass for premium (paid Minecraft) players
  # Premium players will NOT need to login/register
  # Only cracked (non-premium) players will be required to authenticate
  enabled: true

# Login Method Choice
login-method-choice:
  # Allow players to choose between PIN or Password login
  # Players with both PIN and Password can select their preferred method
  enabled: true

# Discord Integration (Webhooks)
discord:
  # Enable Discord webhook notifications for login/registration logs
  enabled: false
  
  # Discord webhook URL for login notifications
  # Create a webhook in your Discord channel settings and paste the URL here
  # Example: "https://discord.com/api/webhooks/123456789/abcdefg..."
  login-webhook: ""
  
  # Discord webhook URL for registration notifications
  # Can be the same as login-webhook or a different one
  registration-webhook: ""
  
  # Log premium player auto-login to Discord
  log-premium-login: true
  
  # Log failed login attempts to Discord
  log-failed-attempts: true
  
  # Webhook customization
  username: "MBTH Security"
  avatar-url: "https://i.imgur.com/AfFp7pu.png"

# PIN Code System
pin-code:
  # Enable PIN code system for extra security
  enabled: true
  
  # Require all players to set up a PIN (Mandatory after registration)
  required: true
  
  # PIN length (number of digits)
  length: 4
  
  # Maximum PIN verification attempts before kick
  max-attempts: 3

# Messages (supports color codes with &)
messages:
  prefix: "&6[&eMBTH&6] &7"
  
  # Welcome Messages
  welcome-premium: "&7Welcome to {server}! You have been automatically authenticated."
  welcome-back: "&7Welcome back to {server}!"
  welcome-registered: "&7Your account is now secured."
  
  # Authentication Prompts
  login-prompt: "&eWelcome back! Please login with &a/login <password>"
  register-prompt: "&eWelcome! Please register with &a/register <password> <confirm>"
  
  # Success Messages
  login-success: "&a&l✔ Successfully logged in!"
  register-success: "&a&l✔ Successfully registered!"
  premium-detected: "&a&l✔ Premium Account Detected!"
  
  # Authentication Status
  already-authenticated: "&cYou are already authenticated!"
  incorrect-password: "&c&l✘ Incorrect password!"
  too-many-attempts: "&cToo many failed attempts!"
  
  # PIN Messages
  pin-prompt: "&eEnter your PIN with &a/verifypin <pin>"
  pin-setup-prompt: "&eSetup your PIN with &a/setuppin <pin> <confirm>"
  pin-verified: "&a&l✔ PIN verified successfully!"
  incorrect-pin: "&c&l✘ Incorrect PIN!"
  
  # Reload Command
  reload-success: "&a&l✔ Configuration Reloaded!"
  reload-details: "&7All settings have been updated from config.yml"